//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IGoDeliverAdmin.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class DeliveryOrder
    {
        public DeliveryOrder()
        {
            this.DeliverOrderRows = new HashSet<DeliverOrderRow>();
            this.Payments = new HashSet<Payment>();
        }
    
        public int OrderId { get; set; }
        public double PriceTotal { get; set; }
        public Nullable<System.DateTime> OrderDateTime { get; set; }
        public string Status { get; set; }
        public Nullable<int> PromoId { get; set; }
        public string OrderRef { get; set; }
        public double DeliveryCost { get; set; }
    
        public virtual ICollection<DeliverOrderRow> DeliverOrderRows { get; set; }
        public virtual Promotion Promotion { get; set; }
        public virtual ICollection<Payment> Payments { get; set; }
    }
}
