//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IGoDeliverAdmin.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class DishPicture
    {
        public int DishId { get; set; }
        public int PictureId { get; set; }
        public bool IsDefault { get; set; }
    
        public virtual Dish Dish { get; set; }
        public virtual PictureOfDish PictureOfDish { get; set; }
    }
}
