//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IGoDeliverAdmin.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class PictureOfRestaurant
    {
        public PictureOfRestaurant()
        {
            this.RestaurantPictures = new HashSet<RestaurantPicture>();
        }
    
        public int Id { get; set; }
        public byte[] Thumbnail { get; set; }
        public string Path { get; set; }
    
        public virtual ICollection<RestaurantPicture> RestaurantPictures { get; set; }
    }
}
