//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IGoDeliverAdmin.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Suburb
    {
        public Suburb()
        {
            this.Geolocations = new HashSet<Geolocation>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public int StateProvince { get; set; }
        public Nullable<int> PostalCode { get; set; }
    
        public virtual ICollection<Geolocation> Geolocations { get; set; }
        public virtual StateProvince StateProvince1 { get; set; }
    }
}
