//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IGoDeliverAdmin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserProfile
    {
        public UserProfile()
        {
            this.Payments = new HashSet<Payment>();
        }
    
        public int UserId { get; set; }
        public string UserName { get; set; }
        public string Phone { get; set; }
        public Nullable<int> LocId { get; set; }
        public string PaypalAcount { get; set; }
        public Nullable<int> CreditCardId { get; set; }
    
        public virtual CreditCard CreditCard { get; set; }
        public virtual Geolocation Geolocation { get; set; }
        public virtual ICollection<Payment> Payments { get; set; }
    }
}
